#id:NXQ_09049
#title:Check there are no entries with kinetic Vmax annotations with evidence NOT from UniProt
#comment:biophysicochemical property
#tags:QC,provenance,function,enzyme
#acs:
#count:0
#time:0.343

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :kineticVmax /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
