#id:NXQ_00261
#title:Glycosylation sites from Glyconnect
#tags:glycosylation,isoforms,PTM,snorql-only,tutorial
#acs:A6NC57,A6NGU5,A6NMZ7 
#count:2679
#time:1.1

select distinct ?entry ?iso ?pos ?comment where {
?entry :isoform ?iso.
?iso  :swissprotDisplayed true .
?iso :sequence / :chain ?seq .
?iso :ptm ?ptm.
?ptm  rdfs:comment ?comment.
?ptm :term ?modterm.
?ptm :start ?pos.
?ptm :evidence / :assignedBy source:GlyConnect. 
} order by ?entry