#id:NXQ_09376
#title:Check there are no entries with redox potential annotations with evidence from UniProt that is negative
#comment:biophysicochemical property
#tags:QC,evidence,negative,function,enzyme
#acs:
#count:0
#time:0.706

select distinct ?entry where {
  ?entry :isoform /:redoxPotential /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
