#id:NXQ_09430
#title:Check there are no entries that do not have a gene name
#tags:QC,gene name
#acs:
#count:0
#time:0.802

select distinct ?entry where {
  ?entry :gene  ?gene .
  filter not exists {?gene :name ?_ }
}
