#id:NXQ_09423
#title:Check there are no entries whose gene is located on chromosome "unknown" which that have a end position which is NOT "0"
#tags:QC,chromosomal location
#acs:
#count:0
#time:0.686

select distinct ?entry where {
  ?entry :gene  ?gene .
  ?gene :chromosome "unknown"^^xsd:string .
  ?gene :end ?end .
  filter (?end = "0"^^xsd:string )
}
