#id:NXQ_09437
#title:Check there are no entries with antibody mapping annotations and no xrefs from HPA
#tags:QC,antibody
#acs:
#count:0
#time:9.391

select distinct ?entry where {
  ?entry :isoform /:antibodyMapping ?map.
  filter not exists {?entry :reference /:provenance db:HPA. }
}
