#id:NXQ_09362
#title:Check there are no entries with nonterminal residue annotations with evidence from UniProt that is negative
#comment:Not displayed
#tags:QC,evidence,negative,sequence
#acs:
#count:0
#time:0.61

select distinct ?entry where {
  ?entry :isoform /:nonTerminalResidue /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
