#id:NXQ_00143
#title:Proteins for which none of the reported proteotypic peptides is from PeptideAtlas nor MassIVE
#tags:dataset,peptide,proteomics,tutorial
#acs:NX_A8MWK0,NX_A8MXK1,NX_Q9H521 
#count:13
#time:27

select ?entry where {
  ?entry :isoform / :peptideMapping ?pm.
  ?pm :proteotypic true .
  ?pm :peptideSource ?src .
  bind (?src = source:MassIVE as ?massive)	   
  bind (?src = source:PeptideAtlas as ?pa)	   
  bind (?src != source:MassIVE && ?src != source:PeptideAtlas as ?other)
} 
group by ?entry
having (sum(?massive)=0 && sum(?pa)=0 && sum(?other)>0)

