#id:NXQ_09220
#title:Check there are no entries with interacting region annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,sequence,region,interaction
#acs:
#count:0
#time:0.618

select distinct ?entry where {
  ?entry :isoform /:interactingRegion /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
