#id:NXQ_09153
#title:Check there are no entries with GO cellular component annotations with evidence from CACAO of quality GOLD
#tags:QC,quality,evidence,cellular component
#acs:
#count:0
#time:0.72

select distinct ?entry where {
  ?entry :isoform /:goCellularComponent /:evidence ?ev1.
  ?ev1 :assignedBy source:CACAO.
  ?ev1 :quality :GOLD.
}
