#id:NXQ_09253
#title:Check there are no entries with sequence caution annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.66

select distinct ?entry where {
  ?entry :isoform /:sequenceCaution /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
