#id:NXQ_09678
#title:Check there are no entries with variant annotations with evidence from gnomAD of quality SILVER
#tags:QC,quality,evidence,variant
#acs:
#count:0
#time:4.14

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev1.
  ?ev1 :assignedBy source:gnomAD.
  ?ev1 :quality :SILVER.
}
