#id:NXQ_00083
#title:Proteins that are expressed only in liver
#tags:expression,tutorial
#acs:O60810,Q92496,O60809 
#count:5
#time:48

Select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :detectedExpression /:term ?tiss, ?tiss2.
  ?tiss2 :childOf cv:TS-0564. # Liver
} group by ?entry ?iso having(count(distinct ?tiss) = count(distinct ?tiss2))


