#id:NXQ_09315
#title:Check there are no entries with caution annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative
#acs:
#count:0
#time:0.701

select distinct ?entry where {
  ?entry :isoform /:caution /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
