#id:NXQ_09182
#title:Check there are no entries with GO cellular component annotations with evidence from SYSCILIA CCNET, the evidence code not IEP and quality SILVER
#tags:QC,quality,evidence,cellular component
#acs:
#count:0
#time:0.762

select distinct ?entry where {
  ?entry :isoform /:goCellularComponent /:evidence ?ev1.
  ?ev1 :assignedBy source:SYSCILIA_CCNET.
  ?ev1 :quality :SILVER.
  filter not exists{?ev1 :evidenceCode cv:ECO_0000270 }
}
limit 10
