#id:NXQ_09378
#title:Check there are no entries with selenocysteine annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,sequence
#acs:
#count:0
#time:0.719

select distinct ?entry where {
  ?entry :isoform /:selenocysteine /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
