#id:NXQ_09324
#title:Check there are no entries with disease annotations with evidence from Orphanet that is negative
#tags:QC,evidence,negative,disease
#acs:
#count:0
#time:0.745

select distinct ?entry where {
  ?entry :isoform /:disease /:evidence ?ev.
  ?ev :assignedBy source:Orphanet.
  ?ev :negative 1.
}
