#id:NXQ_09256
#title:Check there are no entries with signal peptide annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.702

select distinct ?entry where {
  ?entry :isoform /:signalPeptide /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
