#id:NXQ_09681
#title:Check there are no entries with a variant annotation with an allele count of 0
#tags:QC,variant
#acs:
#count:0
#time:0.335

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :variant /:evidence ?ev.
  ?ev :allele-count ?count.
  filter (?count = 0)
}
