#id:NXQ_09655
#title:Check there are no entries with a peptide mapping annotation with evidence from MassIVE but no xref to MassIVE
#tags:QC,mass spectrometry,peptide,proteomics,cross-reference
#acs:
#count:0
#time:58.51

select distinct ?entry where {
  ?entry a :Entry.
  ?entry :isoform /:peptideMapping /:evidence /:assignedBy ?src.
  filter (regex (?src,'MassIVE'))
  filter not exists {?entry :reference /:provenance db:MassIVE.}
}
