#id:NXQ_09091
#title:Check there are no entries with absorption note annotations with evidence from UniProt of quality SILVER
#comment:biophysicochemical property
#tags:QC,quality,evidence
#acs:
#count:0
#time:0.717

select distinct ?entry where {
  ?entry :isoform / :absorptionNote /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
