#id:NXQ_00227
#title:Proteins with at least 2 peptides >=9aa found in testis, but with no peptide identified in sperm [lost during sperm maturation]
#tags:dataset,peptide,proteomics,tutorial
#acs:Q96BJ3,O43715,P61927
#count:6012
#time:700

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :peptideMapping ?pm .
  ?pm :proteotypic true .
  ?pm  :start ?p1 ; :end ?p2 .
  ?pm :evidence / :assignedBy  source:PeptideAtlas_human_Testis.
  filter(?p2-?p1 >= 8) #peplen >= 9
  filter not exists {
    ?iso :peptideMapping ?pm2 .
    ?pm2 :proteotypic true .
    ?pm2 :evidence / :assignedBy  source:PeptideAtlas_human_Sperm_cell.
    }
}
group by ?entry having(count (distinct ?pm) > 1) # at least two such peptides
