#id:NXQ_00231
#title:Proteins with sequences 100% identical to other proteins
#tags:sequence,tutorial
#acs:A0JP26,B3EWG6,B3EWG6
#count:100
#time:0.5

select distinct ?entry where {
  ?entry :isoform / :sequence / :chain ?chain1.
  ?entry2 :isoform / :sequence / :chain ?chain2.
  filter ( (?chain1 = ?chain2) && (?entry != ?entry2))
}