#id:NXQ_09479
#title:Check there are no entries with the Swiss-Prot keyword Bacteriochlorophyll (KW-0076)
#tags:QC,keyword
#acs:
#count:0
#time:0.856

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0076.
}
