#id:NXQ_09573
#title:Check there are no entries with the Swiss-Prot keyword Fibrinogenolytic toxin (KW-1206)
#tags:QC,keyword
#acs:
#count:0
#time:0.784

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-1206.
}
