#id:NXQ_09689
#title:Check there are no entries with expression profile annotations with evidence from Bgee to an anatomy term which is different from the anatomy term in the experimental context
#tags:QC,expression
#acs:
#count:0
#time:22.106

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :expressionProfile ?exp.
  ?exp :term ?term1.
  ?exp :evidence ?ev.
  ?ev :assignedBy source:Bgee.
  ?ev :experimentalContext /:tissue ?term2.
  filter (?term1 != ?term2)
}
