#id:NXQ_09234
#title:Check there are no entries with mutagenesis annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:2.624

select distinct ?entry where {
  ?entry :isoform /:mutagenesis /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
