#id:NXQ_00118
#title:Proteins with at least one somatic variant
#tags:unpublished,variant
#acs:Q9UQ05,O15075,O43166
#count:1382
#time:0.5

#Does not take into account COSMIC variants, not sure it can be done
select distinct ?entry where {
 ?entry :isoform ?iso.
 ?iso :variant ?var.
 ?var rdfs:comment ?comment.
 filter (contains (?comment,'somatic'))
}
