#id:NXQ_09106
#title:Check there are no entries with developmental stage information annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,expression
#acs:
#count:0
#time:0.686

select distinct ?entry where {
  ?entry :isoform / :developmentalStageInfo /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
