#id:NXQ_09270
#title:Check there are no entries with variant annotations with evidence from neXtProt of quality SILVER
#tags:QC,quality,evidence,variant
#acs:
#count:0
#time:0.662

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev1.
  ?ev1 :assignedBy source:NextProt.
  ?ev1 :quality :SILVER.
}
