#id:NXQ_09477
#title:Check there are no entries with the Swiss-Prot keyword Bacterial host gene expression shutoff by virus (KW-1261)
#tags:QC,keyword
#acs:
#count:0
#time:0.817

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-1261.
}
