#id:NXQ_09115
#title:Check there are no entries with expression information annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,expression
#acs:
#count:0
#time:0.716

select distinct ?entry where {
  ?entry :isoform /:expressionInfo /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
