#id:NXQ_09634
#title:Check there are no entries with a variant annotation with the end less than 1
#tags:QC,variant
#acs:
#count:0
#time:0.599

select distinct ?entry where {
  ?entry :isoform /:variant ?var.
  ?var :end ?end.
  filter ( ?end < 1)
}
