#id:NXQ_09230
#title:Check there are no entries with miscellaneous region annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,sequence,region
#acs:
#count:0
#time:0.788

select distinct ?entry where {
  ?entry :isoform /:miscellaneousRegion /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
