#id:NXQ_09269
#title:Check there are no entries with variant annotations with evidence from COSMIC of quality GOLD
#tags:QC,quality,evidence,variant 
#acs:
#count:0
#time:0.77

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev1.
  ?ev1 :assignedBy source:Cosmic.
  ?ev1 :quality :GOLD.
}
