#id:NXQ_00255
#title:Variants identified in exome datasets with a frequency of >0.1
#tags:variant,snorql-only,tutorial
#acs:P35555,O75366,Q09666 
#count:10909
#time:1.2

select distinct ?entry ?varpos ?freq where
{
 ?entry :isoform ?iso . 
 ?iso :swissprotDisplayed true .
 ?iso :variant ?var . 
 ?var :start ?varpos . 
 ?var :evidence ?ev .
 ?ev :alleleNumber ?anb .
 ?ev :alleleFrequency ?freq . 
 filter(?freq > 0.1 && ?anb > 100000) 
 } order by desc(?freq)
