#id:NXQ_09397
#title:Check there are no entries with variant annotations with evidence from Cosmic that is negative
#tags:QC,evidence,negative,variant
#acs:
#count:0
#time:0.717

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev.
  ?ev :assignedBy source:Cosmic.
  ?ev :negative 1.
}
