#id:NXQ_09281
#title:Check there are no entries with expression profile annotations from Bgee for which the evidence code is NOT microarray RNA expression level evidence (ECO:0000104) or transcript expression evidence (ECO:0000009)
#tags:QC,evidence,ECO
#acs:
#count:0
#time:7.39

select distinct ?entry where {
  ?entry :isoform /:expressionProfile /:evidence ?ev1.
  ?ev1 :assignedBy source:Bgee.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0000104, cv:ECO_0000009))
}
