#id:NXQ_09659
#title:Check there are no entries with GO molecular function annotations with evidence having the evidence code IBA and quality GOLD
#comment:ECO:0000318 Inferred from Biological aspect of Ancestor (IBA)
#tags:QC,quality,evidence,function
#acs:
#count:0
#time:0.416

select distinct ?entry where {
  ?entry :isoform /:goMolecularFunction /:evidence ?ev1.
  ?ev1 :evidenceCode cv:ECO_0000318.
  ?ev1 :quality :GOLD.
}
