#id:NXQ_09406
#title:Check there are no entries with GO cellular component annotations with the evidence code is ND (ECO:0000035)
#tags:QC,filtering,evidence
#acs:
#count:0
#time:0.733

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :goCellularComponent /:evidence /:evidenceCode cv:ECO_0000035.
}
