#id:NXQ_09029
#title:Check there are no entries with domain information annotations with evidence NOT from UniProt
#tags:QC,provenance,sequence
#acs:
#count:0
#time:0.553

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :domainInfo /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
