#id:NXQ_09254
#title:Check there are no entries with sequence conflict annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.97

select distinct ?entry where {
  ?entry :isoform /:sequenceConflict /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
