#id:NXQ_00245
#title:Proteins with a propeptide 
#tags:processing,sequence,tutorial
#acs:H3BQJ8,A6ND01,O00526
#count:734
#time:1.2


select distinct ?entry where  {
  ?entry :isoform / :propeptide ?propep .
}
