#id:NXQ_09461
#title:Check there are no entries with a ptm info annotation referring to glycosylation that do not have the keyword Glycoprotein (KW-0325)
#tags:QC,keyword
#acs:O00327,A1KXE4,Q6PRD7 
#count:8
#time:1.008

select distinct ?entry where {  # Include ?text if result is not 0 to identify problem site
  ?entry :isoform ?iso.
  ?iso :ptmInfo /rdfs:comment ?text.
  filter(contains(?text,"glycosylat")). # Finds glycosylated and glycosylation
  filter not exists {?iso :ptmInfo /:negativeEvidence ?negev} # No negative annotations from neXtProt
  filter not exists {?entry :isoform /:keyword /:term cv:KW-0325.}  
  filter (?entry not in (entry:NX_O43866, entry:NX_P60827, entry:NX_O75452, entry:NX_P60033, entry:NX_Q01628, entry:NX_O75192, entry:NX_Q8TCT6, entry:NX_Q86TM6, entry:NX_Q8TC12, entry:NX_P49788, entry:NX_Q9NUD9, entry:NX_P47710, entry:NX_Q8IY95, entry:NX_Q02447, entry:NX_P49238, entry:NX_Q9BSG5, entry:NX_Q8TF71, entry:NX_P51811, entry:NX_Q9UBT3, entry:NX_Q9UBY8)) # Exceptions to rule (not glycosylated)
}
