#id:NXQ_09611
#title:Check there are no entries with glycosylation site annotations from GlyConnect for which the evidence code is NOT experimental evidence used in manual assertion
#tags:QC,evidence,ECO,PTM
#acs:
#count:0
#time:0.764

select distinct ?entry where {
  ?entry :isoform /:glycosylationSite /:evidence ?ev1.
  ?ev1 :assignedBy source:GlyConnect.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0000269))
}
