#id:NXQ_00002
#title:Proteins that are located in both the nucleus and in the cytoplasm
#tags:subcellular location,cellular component,tutorial
#acs:A0AVF1,A0PK00,A1A4S6,A1A5C7,A1KXE4,A2RRD8
#count:6305

select distinct ?entry where {
  values ?cytoloc {cv:GO_0005737 cv:SL-0086} # GO and SL values for cytoplasm
  values ?nucloc {cv:GO_0005634 cv:SL-0191} # GO and SL values for nucleus
  ?entry :isoform ?iso.
  ?iso :cellularComponent ?loc1, ?loc2 .
  ?loc1 :term /:childOf ?cytoloc .
  ?loc2 :term /:childOf ?nucloc .
  filter not exists {?loc1  :negativeEvidence ?negev} # No negative localization evidence
  filter not exists {?loc2  :negativeEvidence ?negev} # No negative localization evidence
}

