#id:NXQ_00267
#title:Proteins binding estradiol and/or similar molecules (similarity search with SMILES), and their associated GO_MF terms
#tags:function,similarity,small molecule interaction,snorql-only,federated query,tutorial
#count:237
#time:24

PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX idsm: <https://idsm.elixir-czech.cz/sparql/endpoint/>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>

SELECT distinct ?entry (group_concat(distinct str(?gomflab); SEPARATOR = ",") as ?gomfx) WHERE {
  		SERVICE <https://idsm.elixir-czech.cz/sparql/endpoint/idsm> {
  		SERVICE <https://idsm.elixir-czech.cz/sparql/endpoint/chembl> {
    		?compound sachem:similarCompoundSearch [ sachem:query "CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O" ] . # smiles chain for estradiol
		  }
		  		?ACTIVITY rdf:type chembl:Activity;
		chembl:hasMolecule ?compound;
            chembl:hasAssay ?ASSAY.
		  ?ASSAY chembl:hasTarget ?TARGET.
		  ?TARGET chembl:taxonomy <http://identifiers.org/taxonomy/9606> . # human protein target
		  ?TARGET chembl:hasTargetComponent ?COMPONENT.
		  ?COMPONENT chembl:targetCmptXref ?UNIPROT.
		  filter(contains(str(?UNIPROT),"uniprot"))
		  }
	?entry skos:exactMatch ?UNIPROT.
	?entry :isoform ?iso.
	?iso :goMolecularFunction / :term ?gomf .
	?gomf rdfs:label ?gomflab .
} 
group by ?entry

