#id:NXQ_DEREF_002
#title:Query for an Isoform Instance e.g isoform:NX_Q8WZ42-1
#tags:deref_instance_Isoform

CONSTRUCT {
     $INSTANCE_ISOFORM :functionInfo ?object .
     ?object rdfs:comment ?comment.
     $INSTANCE_ISOFORM :canonicalIsoform ?isCanonical.
} WHERE {
     $INSTANCE_ISOFORM :functionInfo ?object .
     ?object rdfs:comment ?comment.
     optional {
          $INSTANCE_ISOFORM :canonicalIsoform ?isCanonical.
     }
     FILTER(!isBlank(?object))
}