#id:NXQ_09097
#title:Check there are no entries with calcium binding region annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,interaction,region,sequence
#acs:
#count:0
#time:0.697

select distinct ?entry where {
  ?entry :isoform /:calciumBindingRegion /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
