#id:NXQ_09255
#title:Check there are no entries with short sequence motif annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence,region
#acs:
#count:0
#time:1.242

select distinct ?entry where {
  ?entry :isoform /:shortSequenceMotif /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
