#id:NXQ_09052
#title:Check there are no entries with metal binding site annotations with evidence NOT from UniProt
#tags:QC,provenance,sequence,interaction
#acs:
#count:0
#time:0.722

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :metalBindingSite /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
