#id:NXQ_09105
#title:Check there are no entries with crosslink annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.744

select distinct ?entry where {
  ?entry :isoform /:crossLink /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
