#id:NXQ_09252
#title:Check there are no entries with selenocysteine annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:1.113

select distinct ?entry where {
  ?entry :isoform /:selenocysteine /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
