#id:NXQ_09263
#title:Check there are no entries with temperature dependence annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,function,enzyme
#acs:
#count:0
#time:0.611

select distinct ?entry where {
  ?entry :isoform /:temperatureDependence /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
