#id:NXQ_09032
#title:Check there are no entries with enzyme regulation annotations with evidence NOT from UniProt
#tags:QC,provenance,function,enzyme
#acs:
#count:0
#time:0.407

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :enzymeRegulation /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
