#id:NXQ_00204
#title:Proteins with PE-2 or PE-3 or PE-4
#tags:
#acs:A6NCI4,..
#count:2775
#time:0.352

select distinct ?entry where {
  values ?level {
#	:Evidence_at_protein_level    # PE-1  
	:Evidence_at_transcript_level # PE-2
	:Inferred_from_homology       # PE-3
	:Predicted                    # PE-4
#	:Uncertain                    # PE-5
    }
  ?entry a :Entry .
  ?entry :existence ?level .
}
