#id:NXQ_09332
#title:Check there are no entries with activity regulation (previously enzyme regulation) annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,function,enzyme
#acs:
#count:0
#time:0.693

select distinct ?entry where {
  ?entry :isoform /:activityRegulation /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
