#id:NXQ_09233
#title:Check there are no entries with modified residue annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,PTM
#acs:
#count:0
#time:0.671

select distinct ?entry where {
  ?entry :isoform /:modifiedResidue /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
