#id:NXQ_09686
#title:Check there are no entries with a variant annotation with evidence from gnomAD that do not have an allele number
#tags:QC,variant
#acs:
#count:0
#time:2.45

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev.
  ?ev :assignedBy source:gnomAD.
  filter not exists {?ev :allele-number ?no.}
}
