#id:NXQ_09672
#title:Check there are no entries with expression profile annotations with evidence from EST which are NOT from Bgee
#tags:QC,provenance,ECO
#acs:
#count:0
#time:0.534

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :expressionProfile /:evidence ?ev.
  ?ev :evidenceCode cv:ECO_0000009. # EST
  filter not exists { ?ev :assignedBy source:Bgee }
}
