#id:NXQ_00046
#title:Proteins with a gene alternative name which is IL27
#tags:gene name
#acs:
#count:
#time:

select distinct ?x ?p ?entry ?name where {
  ?entry a :Entry.
  ?entry :alternativeName /:fullName ?name.
  filter (strlen(?name) < 5 )
}
