#id:NXQ_09320
#title:Check there are no entries with compositionally biased region annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,sequence,region
#acs:
#count:0
#time:0.744

select distinct ?entry where {
  ?entry :isoform /:compositionallyBiasedRegion /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
