#id:NXQ_09357
#title:Check there are no entries with modified residue annotations with evidence from neXtProt that is negative
#comment:neXtProt MDATA
#tags:QC,evidence,negative,PTM
#acs:
#count:0
#time:2.564

select distinct ?entry where {
  ?entry :isoform /:modifiedResidue /:evidence ?ev.
  ?ev :assignedBy source:NextProt.
  ?ev :negative 1.
}
