#id:NXQ_09277
#title:Check there are no entries with crosslink annotations from neXtProt for which the evidence code is NOT mass spectrometry evidence
#tags:QC,evidence,ECO,sequence
#acs:
#count:0
#time:0.732

select distinct ?entry where {
  ?entry :isoform / :crossLink /:evidence ?ev1.
  ?ev1 :assignedBy source:NextProt.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0001096))
}
