#id:NXQ_09411
#title:Check there are no entries with no chromosome location
#tags:QC,chromosomal location
#acs:
#count:0
#time:0.695

select distinct ?entry where {
  ?entry :gene  ?gene .
  filter not exists {?gene :chromosome ?_ }
}
