#id:NXQ_09374
#title:Check there are no entries with propeptide annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,sequence
#acs:
#count:0
#time:0.8

select distinct ?entry where {
  ?entry :isoform /:propeptide /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
