#id:NXQ_09458
#title:Check there are no entries with the Swiss-Prot keyword Swiss-Prot keyword Antenna complex (KW-0042)
#tags:QC,keyword
#acs:
#count:0
#time:0.798

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0042.
}
