#id:NXQ_09119
#title:Check there are no entries with function information annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,function
#acs:
#count:0
#time:0.664

select distinct ?entry where {
  ?entry :isoform /:functionInfo /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
