#id:NXQ_09636
#title:Check there are no entries with a variant annotation with the end less than the start
#tags:QC,variant
#acs:
#count:0
#time:8.018

select distinct ?entry where {
  ?entry :isoform /:variant ?var.
  ?var :start ?start.
  ?var :end ?end.
  filter ( ?end < ?start)
}
