#id:NXQ_09042
#title:Check there are no entries with initiator methionine annotations with evidence NOT from UniProt
#tags:QC,provenance,sequence
#acs:
#count:0
#time:0.298

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :initiatorMethionine /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
