#id:NXQ_09248
#title:Check there are no entries with propeptide annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.67

select distinct ?entry where {
  ?entry :isoform /:propeptide /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
