#id:NXQ_00226
#title:Proteins with at least 2 validating peptides >=9aa found in blood plasma, urine or cerebrospinal fluid (criteria for biomarker)].
#tags:dataset,peptide,proteomics,tutorial
#acs:entry:Q8WYA6,Q8N8Y2,P13746
#count:9717
#time:24

select distinct ?entry where { 
values ?pepsources { 
        source:PeptideAtlas_human_Cerebrospinal_Fluid 
        source:PeptideAtlas_human_Blood_Plasma 
        source:PeptideAtlas_human_Urine 
        source:MassIVE_human_Cerebrospinal_Fluid 
        source:MassIVE_human_Blood_Plasma 
        source:MassIVE_human_Urine 
        } 
  ?entry :isoform ?iso. 
  ?iso :peptideMapping ?pm . 
  ?pm :peptideName ?pepid .
  ?pm :evidence / :assignedBy ?pepsources . 
  ?pm :proteotypic true . 
  ?pm  :start ?p1 ; :end ?p2 . 
  filter(?p2-?p1 >= 8) # peptide length >= 9 
} 
group by ?entry having(count (distinct ?pepid) > 1) # at least two such peptides 