#id:NXQ_09444
#title:Check there are no entries with a keyword in the category "Technical term" that does not apply to human proteins
#tags:QC,keyword
#acs:
#count:0
#time:0.828

select distinct ?entry where {  # Include ?kw if result is not 0 to identify problem keyword
  values ?kw {
  cv:KW-0181 # Complete proteome
  cv:KW-0952 # Extinct organism protein
  cv:KW-0308 # Genetically modified food
  cv:KW-0374 # Hybridoma
  cv:KW-0614 # Plasmid
  cv:KW-1185 # Reference proteome
  }
  ?entry :isoform /:keyword /:term ?kw.
}
