#id:NXQ_09467
#title:Check there are no entries with the Swiss-Prot keyword Aromatic amino acid biosynthesis (KW-0057)
#tags:QC,keyword
#acs:
#count:0
#time:0.824

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0057.
}
