#id:NXQ_00235
#title:Proteins with at least two antibodies available from Human Protein Atlas that have associated tissue expression annotations from immunohistochemistry studies 
#tags:antibody,expression,method,tutorial
#acs:A0AUZ9,A0AVF1,A0JNW5
#count:5105
#time:52

select distinct ?entry where {
 ?entry :isoform ?iso.
 ?iso :antibodyMapping ?abmap.
 ?abmap :evidence / :reference / :accession ?aid .
 ?iso :expressionProfile / :evidence ?ev .
 ?ev :evidenceCode cv:ECO_0001055.
# ?ev :quality :GOLD .
}
group by ?entry having(count(distinct ?aid) > 1)
order by ?entry
