#id:NXQ_09542
#title:Check there are no entries with the Swiss-Prot keyword Cytochrome c-type biogenesis (KW-0201)
#tags:QC,keyword
#acs:
#count:0
#time:0.839

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0201.
}
