#id:NXQ_09398
#title:Check there are no entries with variant annotations with evidence from dbSNP that is negative
#tags:QC,evidence,negative,variant
#acs:
#count:0
#time:0.645

select distinct ?entry where {
  ?entry :isoform /:variant /:evidence ?ev.
  ?ev :assignedBy source:dbSNP.
  ?ev :negative 1.
}
