#id:NXQ_09321
#title:Check there are no entries with cross-link annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,sequence
#acs:
#count:0
#time:0.738

select distinct ?entry where {
  ?entry :isoform /:crossLink /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
