#id:NXQ_09190
#title:Check there are no entries with GO molecular function annotations with evidence from LIFEdb of quality GOLD
#tags:QC,quality,evidence,function
#acs:
#count:0
#time:0.751

select distinct ?entry where {
  ?entry :isoform /:goMolecularFunction /:evidence ?ev1.
  ?ev1 :assignedBy source:LIFEdb.
  ?ev1 :quality :GOLD.
}
