#id:NXQ_09347
#title:Check there are no entries with kinetic note annotations with evidence from UniProt that is negative
#comment:biophysicochemical property
#tags:QC,evidence,negative,function,enzyme
#acs:
#count:0
#time:0.715

select distinct ?entry where {
  ?entry :isoform /:kineticNote /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
