#id:NXQ_09434
#title:Check there are no entries with PDB mapping annotation and no xref to PDBsum
#tags:QC,3D structure
#acs:
#count:0
#time:0.619

select distinct ?entry where {
  ?entry :isoform /:pdbMapping ?map.
  filter not exists {?entry :reference /:provenance db:PDBsum.}
}
