#id:NXQ_09293
#title:Check there are no entries with *peptide mapping* annotations from neXtProt for which the evidence code is NOT mass spectrometry evidence
#tags:QC,evidence,ECO,mass spectrometry,peptide,proteomics
#acs:
#count:0
#time:0.765

select distinct ?entry where {
  ?entry :isoform /:peptideMapping /:evidence ?ev1.
  ?ev1 :assignedBy source:NextProt.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0001096))
}
