#id:NXQ_09013
#title:Check there are no entries with binding site annotations with evidence NOT from UniProt
#tags:QC,provenance,interaction,sequence
#acs:
#count:0
#time:0.694

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :bindingSite /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
