#id:NXQ_09227
#title:Check there are no entries with mature protein annotations with evidence from UniProt of quality SILVER
#comment:mature chain
#tags:QC,quality,evidence,sequence
#acs:
#count:0
#time:0.596

select distinct ?entry where {
  ?entry :isoform /:matureProtein /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
