#id:NXQ_09470
#title:Check there are no entries with the Swiss-Prot keyword Aspartyl esterase (KW-0063)
#tags:QC,keyword
#acs:
#count:0
#time:0.975

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0063.
}
