#id:NXQ_09107
#title:Check there are no entries with disease annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,disease
#acs:
#count:0
#time:0.677

select distinct ?entry where {
  ?entry :isoform / :disease /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
