#id:NXQ_09062
#title:Check there are no entries with pathway annotations with evidence NOT from KEGG Pathway, Reactome or UniProt
#tags:QC,provenance,function
#acs:
#count:0
#time:0.619

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :pathway /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:KEGG_PTW,source:Reactome,source:Uniprot))
}
