#id:NXQ_00250
#title:Proteins that act as transporters and their TCDB numbers
#tags:function,snorql-only,tutorial,xref
#acs:Q99250,Q14524,P35499
#count:1587
#time:7

select distinct ?entry str(?trcom) str(?acc) {
  ?entry :isoform/ :transportActivity ?tr.
  ?tr rdfs:comment ?trcom;  :evidence / :reference ?ref.
  ?ref a :Xref; :accession ?acc .
} order by ?acc
