#id:NXQ_09446
#title:Check there are no entries with the Swiss-Prot keyword Acetoin catabolism (KW-0006)
#tags:QC,keyword
#acs:
#count:0
#time:0.913

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0006.
}
