#id:NXQ_00026
#title:Proteins interacting with at least one protein which is located in the mitochondrion
#tags:interaction,PPI,subcellular location,cellular component
#acs:A0JLT2,A0PJW6,A2A2Y4,O00193,O00198,O00217,O00220,O00221,O00231,O00254
#count:2161
#time:4

select distinct ?entry where {
  ?entry :isoform / :interaction ?it .
  ?it :quality :GOLD . # remove this filter for lower quality interactions
  ?it :interactant ?interactant.
  # the question mark at :isoform allows to select also isoform-specific interactions
  ?interactant :isoform? / :cellularComponent / :term / :childOf /^:related cv:SL-0173
}
