#id:NXQ_09529
#title:Check there are no entries with the Swiss-Prot keyword Complement system impairing toxin (KW-1216)
#tags:QC,keyword
#acs:
#count:0
#time:0.888

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-1216.
}
