#id:NXQ_09251
#title:Check there are no entries with repeat annotations with evidence from Uniprot of quality SILVER
#tags:QC,quality,evidence,sequence,repeats
#acs:
#count:0
#time:0.736

select distinct ?entry where {
  ?entry :isoform /:repeat /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
