#id:NXQ_09048
#title:Check there are no entries with kinetic note annotations with evidence NOT from UniProt
#comment:biophysicochemical property
#tags:QC,provenance,function,enzyme
#acs:
#count:0
#time:0.29

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :kineticNote /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
