#id:NXQ_09008
#title:Check there are no entries with active site annotations with evidence NOT from UniProt
#tags:QC,provenance,active site
#acs:
#count:0
#time:0.752

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :ActiveSite /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
