#id:NXQ_09282
#title:Check there are no entries with expression profile annotations from HPA for which the evidence code is NOT immunohistochemistry evidence (ECO:0001055)
#tags:QC,evidence,ECO,expression
#acs:
#count:0
#time:4.664

select distinct ?entry where {
  ?entry :isoform /:expressionProfile /:evidence ?ev1.
  ?ev1 :assignedBy source:Human_protein_atlas.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0001055))
}
