#id:NXQ_00223
#title:100 most-cited publications in neXtProt and the corresponding number of associated entries
#tags:publication,snorql-only,tutorial
#acs:PubMed:15489334","PubMed:24755471","PubMed:25303977"
#count:100
#time:24

select (str(?publiid) as ?PMID) (str(?tt) as ?title) (count(distinct ?entry) as ?ecnt) 
where {
  ?entry a :Entry .
  ?entry :reference ?ref .
   ?ref a :Publication.
   ?ref :title ?tt .
   ?ref :from ?xref .
   ?xref :accession ?publiid .
   ?xref :provenance db:PubMed .
}
group by ?publiid ?tt
order by desc(?ecnt)
limit 100