#id:NXQ_09087
#title:Check there are no entries with variant annotations with evidence NOT from Cosmic, dbSNP, gnomAD, neXtProt or UniProt
#comment:neXtProt BioEditor data
#tags:QC,provenance,variant
#acs:
#count:0
#time:29.818

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :variant /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Cosmic,source:dbSNP,source:gnomAD,source:NextProt,source:Uniprot))
}
