#id:NXQ_09073
#title:Check there are no entries with selenocysteine annotations with evidence NOT from UniProt
#tags:QC,provenance,sequence
#acs:
#count:0
#time:0.643

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :selenocysteine /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
