#id:NXQ_09594
#title:Check there are no entries with the Swiss-Prot keyword Genetically modified food (KW-0308)
#tags:QC,keyword
#acs:
#count:0
#time:0.911

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0308.
}
