#id:NXQ_09222
#title:Check there are no entries with intramembrane region annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,region,subcellular location
#acs:
#count:0
#time:0.692

select distinct ?entry where {
  ?entry :isoform /:intramembraneRegion /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
