#id:NXQ_09497
#title:Check there are no entries with the Swiss-Prot keyword Calvin cycle (KW-0113)
#tags:QC,keyword
#acs:
#count:0
#time:0.876

select distinct ?entry where {
  ?entry :isoform /:keyword / :term cv:KW-0113.
}
