#id:NXQ_09631
#title:Check there are no entries with small molecule interaction annotations with evidence from DrugBank of quality GOLD
#tags:QC,quality,evidence,interaction
#acs:
#count:0
#time:0.412

select distinct ?entry where {
  ?entry :isoform /:smallMoleculeInteraction /:evidence ?ev1.
  ?ev1 :assignedBy source:DrugBank.
  ?ev1 :quality :GOLD.
}
