#id:NXQ_00075
#title:Proteins which have been detected in the HUPO liver proteome set but not the HUPO plasma proteome set
#tags:expression,dataset,proteomics,mass spectrometry,tutorial
#acs:A6NC98 , A6NK58 , O95848 ,...
#count:732
#time: 27s

select distinct ?entry where {
  ?entry a :Entry.
  ?entry :isoform / :peptideMapping / :evidence / :assignedBy source:PeptideAtlas_human_Liver .
  filter not exists { ?entry :isoform / :peptideMapping / :evidence / :assignedBy source:PeptideAtlas_human_Blood_Plasma . }
}
