#id:NXQ_09403
#title:Check there are no entries that have the accession number of excluded UniProt entries
#tags:QC,filtering
#acs:
#count:0
#time:0.917

select distinct ?entry where {
  values ?ac
  {"P04437" "P01737" "P01733" "P04435"} # space-separated list of 4 excluded UniProt primary ACs
  ?entry :reference ?ref.
  ?ref :provenance db:UniProt.
  ?ref :accession ?ac.
}
