#id:NXQ_09031
#title:Check there are no entries with enzyme classification annotations with evidence NOT from UniProt
#tags:QC,provenance,function,enzyme
#acs:
#count:0
#time:0.517

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :enzymeClassification /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
