#id:NXQ_09323
#title:Check there are no entries with developmental stage information annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,expression
#acs:
#count:0
#time:0.624

select distinct ?entry where {
  ?entry :isoform /:developmentalStageInfo /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
