#id:NXQ_09007
#title:Check there are no entries with absorption note annotations with evidence NOT from UniProt
#comment:biophysicochemical property
#tags:QC,provenance
#acs:
#count:0
#time:0.773

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :AbsorptionNote /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
