#id:NXQ_09163
#title:Check there are no entries with GO cellular component annotations with evidence from Alzheimers University of Toronto of quality SILVER and evidence code not IBA, IEP, HMP, HDA or HEP
#tags:QC,quality,evidence,cellular component
#acs:
#count:0
#time:0.788

select distinct ?entry where {
  ?entry :isoform /:goCellularComponent /:evidence ?ev.
  ?ev :assignedBy source:Alzheimers_University_of_Toronto.
  ?ev :quality :SILVER.
  ?ev :evidenceCode ?eco.
  filter ( ?eco not in ( cv:ECO_0000318,cv:ECO_0000270,cv:ECO_0007001,cv:ECO_0007005,cv:ECO_0007007 ))
}
