#id:NXQ_09367
#title:Check there are no entries with PDB mapping annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,3D structure
#acs:
#count:0
#time:0.719

select distinct ?entry where {
  ?entry :isoform /:pdbMapping /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
