#id:NXQ_09372
#title:Check there are no entries with pharmaceutical annotations with evidence from UniProt that is negative
#tags:QC,evidence,negative,pharmaceutical
#acs:
#count:0
#time:0.865

select distinct ?entry where {
  ?entry :isoform /:pharmaceutical /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
