#id:NXQ_09102
#title:Check there are no entries with cofactor information annotations with evidence from UniProt of quality SILVER
#tags:QC,quality,evidence,function,enzyme
#acs:
#count:0
#time0.597

select distinct ?entry where {
  ?entry :isoform /:cofactorInfo /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
