#id:NXQ_09076
#title:Check there are no entries with short sequence motif annotations with evidence NOT from UniProt
#tags:QC,provenance,sequence,region
#acs:
#count:0
#time:0.752

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :shortSequenceMotif /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
