







































#id:NXQ_00129
#title:Proteins without a lysine in the mature chain
#tags:unpublished,sequence
#acs:Q8TDT2,O75177,Q86UN3
#count:338
#time:0.9

SELECT distinct ?entry ?recname ?mlen WHERE  {
?entry :recommendedName /:fullName ?recname.
?entry :isoform ?iso .
?iso :matureProtein [ :start ?mstart ; :end ?mend].
?iso  :sequence /:chain ?seq.	 
FILTER (?mend-?mstart > 0). # chain fully defined
BIND(?mend - ?mstart as ?mlen)	 
BIND(substr(?seq, ?mstart, ?mlen) as ?mseq)	 
filter(!regex (?mseq,'K'))
}
order by desc(?mlen)
